# Generated by Django 3.2.4 on 2021-06-19 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre de la parroquia')),
                ('tipo', models.CharField(choices=[('urbana', 'Parroquia Urbana'), ('rural', 'Parroqua Rural')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Parroquias',
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del barrio')),
                ('nroViviendas', models.IntegerField(verbose_name='Número de vivendas')),
                ('nroParques', models.IntegerField(choices=[(1, 'Un parque'), (2, 'Dos parques'), (3, 'Tres parques'), (4, 'Cuatro parques'), (5, 'Cinco parques'), (6, 'Seis parques')], verbose_name='Número de parques')),
                ('nroEdificios', models.IntegerField(verbose_name='Número de edificios')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parroquias', to='ordenamiento.parroquia')),
            ],
            options={
                'verbose_name_plural': 'Barrios',
            },
        ),
    ]
